name: houses-of-light-request-system
# DATABASE FIX - FORCE DEPLOYMENT - TIMESTAMP 2025-08-09T03:25
services:
  - name: backend
    source_dir: backend
    github:
      repo: ayoantar/HOL-ticket_system
      branch: main
      deploy_on_push: true
    build_command: npm ci
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 5002
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5002"
      - key: CLIENT_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: EMAIL_HOST
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: EMAIL_PORT
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: EMAIL_USER
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: EMAIL_PASS
        scope: RUN_AND_BUILD_TIME
        type: SECRET

  - name: frontend
    source_dir: frontend
    github:
      repo: ayoantar/HOL-ticket_system
      branch: main
      deploy_on_push: true
    build_command: CI=false npm run build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 80
    routes:
      - path: /
    static_sites:
      - name: frontend-static
        source_dir: build
        index_document: index.html
        error_document: index.html

databases:
  - name: hol-postgresql
    engine: PG
    version: "14"
    num_nodes: 1
    size: db-s-dev-database

alerts:
  - rule: CPU_UTILIZATION
    value: 80
  - rule: MEM_UTILIZATION
    value: 80